"""Change column name in menu table

Revision ID: 5f96807f0951
Revises: 6b991d925ae4
Create Date: 2023-06-04 17:23:43.041296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f96807f0951'
down_revision = '6b991d925ae4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.drop_constraint('menu_menu_id_fkey', 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'restaurant', ['restaurant_id'], ['id'])
    op.drop_column('menu', 'menu_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.create_foreign_key('menu_menu_id_fkey', 'menu', 'restaurant', ['menu_id'], ['id'])
    op.drop_column('menu', 'restaurant_id')
    # ### end Alembic commands ###
