"""change menu table

Revision ID: 6b991d925ae4
Revises: 803ac9cc8d66
Create Date: 2023-06-03 18:10:37.633113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b991d925ae4'
down_revision = '803ac9cc8d66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.add_column('menu', sa.Column('menu', sa.JSON(), nullable=False))
    op.drop_constraint('menu_id_branch_fkey', 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'restaurant', ['menu_id'], ['id'])
    op.drop_column('menu', 'size')
    op.drop_column('menu', 'currency')
    op.drop_column('menu', 'allergens')
    op.drop_column('menu', 'id')
    op.drop_column('menu', 'nutritional_values')
    op.drop_column('menu', 'price')
    op.drop_column('menu', 'category_name')
    op.drop_column('menu', 'ingredients')
    op.drop_column('menu', 'id_branch')
    op.drop_column('menu', 'dish_name')
    op.drop_column('menu', 'dish_picture_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('dish_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('dish_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('id_branch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('ingredients', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('nutritional_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('menu', sa.Column('allergens', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.create_foreign_key('menu_id_branch_fkey', 'menu', 'branch', ['id_branch'], ['id'])
    op.drop_column('menu', 'menu')
    op.drop_column('menu', 'menu_id')
    # ### end Alembic commands ###
