"""Create table

Revision ID: 70d8d728dd68
Revises: 
Create Date: 2023-06-20 18:31:54.697316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70d8d728dd68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen',
    sa.Column('allergen_id', sa.String(), nullable=False),
    sa.Column('allergen_name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('allergen_id')
    )
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('food',
    sa.Column('food_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dish_picture_url', sa.String(), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diet_restriction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutritional_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('size', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_ingredients', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('diet_restriction', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('metric_system', sa.String(), nullable=False),
    sa.Column('allergens', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('food_allergens',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen.allergen_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.food_id'], ),
    sa.PrimaryKeyConstraint('food_id', 'allergen_id')
    )
    op.create_table('user_history',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_food', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_food'], ['food.food_id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_table('food_allergens')
    op.drop_table('user_preferences')
    op.drop_table('food')
    op.drop_table('user')
    op.drop_table('restaurant')
    op.drop_table('allergen')
    # ### end Alembic commands ###
