"""Create database

Revision ID: 803ac9cc8d66
Revises: 
Create Date: 2023-06-03 15:13:14.548865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803ac9cc8d66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('user_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('branch',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('id_restaurant', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurant.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('preferred_ingredients', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('allergens', sa.ARRAY(sa.String()), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
                    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('menu',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('category_name', sa.String(), nullable=False),
                    sa.Column('dish_name', sa.String(), nullable=False),
                    sa.Column('dish_picture_url', sa.String(), nullable=True),
                    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=False),
                    sa.Column('allergens', sa.ARRAY(sa.String()), nullable=False),
                    sa.Column('nutritional_values', sa.JSON(), nullable=True),
                    sa.Column('size', sa.Float(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('currency', sa.String(), nullable=False),
                    sa.Column('id_branch', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id_branch'], ['branch.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('user_preferences')
    op.drop_table('branch')
    op.drop_table('user')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
